# #
#   @project              Docker Image › Alpine Base › Docker-compose.yml
#   @usage                base image utilized for all docker images using Alpine with s6-overlay integration
#   @file                 docker-compose.yml
#   @repo                 https://github.com/aetherinox/docker-base-alpine
#
#   @image:github         ghcr.io/aetherinox/ubuntu:latest
#                         ghcr.io/aetherinox/ubuntu:22.04
#                         ghcr.io/aetherinox/ubuntu:noble
#
#   @image:dockerhub      aetherinox/ubuntu:latest
#                         aetherinox/ubuntu:22.04
#                         aetherinox/ubuntu:noble
#
#                         AMD64
#                         Build the image with:
#                             docker buildx build \
#                               --build-arg IMAGE_NAME=alpine \
#                               --build-arg IMAGE_ARCH=amd64 \
#                               --build-arg IMAGE_BUILDDATE=20260812 \
#                               --build-arg IMAGE_VERSION=3.22 \
#                               --build-arg IMAGE_RELEASE=stable \
#                               --build-arg IMAGE_REGISTRY=github \
#                               --tag aetherinox/alpine:latest \
#                               --tag aetherinox/alpine:3 \
#                               --tag aetherinox/alpine:3.2 \
#                               --tag aetherinox/alpine:3.22 \
#                               --tag aetherinox/alpine:amd64 \
#                               --attest type=provenance,disabled=true \
#                               --attest type=sbom,disabled=true \
#                               --output type=docker \
#                               --builder default \
#                               --file Dockerfile \
#                               --platform linux/amd64 \
#                               --allow network.host \
#                               --network host \
#                               --no-cache \
#                               --progress=plain \
#                               .
#
#                         ARM64
#                         For arm64, make sure you install QEMU first in docker; use the command:
#                             docker run --privileged --rm tonistiigi/binfmt --install all
#
#                         Build the image with:
#                             docker buildx build \
#                               --build-arg IMAGE_NAME=alpine \
#                               --build-arg IMAGE_ARCH=arm64 \
#                               --build-arg IMAGE_BUILDDATE=20260812 \
#                               --build-arg IMAGE_VERSION=3.22 \
#                               --build-arg IMAGE_RELEASE=stable \
#                               --build-arg IMAGE_REGISTRY=github \
#                               --tag aetherinox/alpine:latest \
#                               --tag aetherinox/alpine:3 \
#                               --tag aetherinox/alpine:3.2 \
#                               --tag aetherinox/alpine:3.22 \
#                               --tag aetherinox/alpine:amd64 \
#                               --attest type=provenance,disabled=true \
#                               --attest type=sbom,disabled=true \
#                               --output type=docker \
#                               --builder default \
#                               --file Dockerfile \
#                               --platform linux/arm64 \
#                               --allow network.host \
#                               --network host \
#                               --no-cache \
#                               --progress=plain \
#                               .
# #

services:

    # #
    #   Service › Alpine
    # #

    base-alpine:
        container_name: base-alpine
        image: aetherinox/alpine:3.22
        hostname: alpine
        environment:
            - TZ=Etc/UTC
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            traefik:
                ipv4_address: '172.18.75.2'

# #
#   Networks
#
#   docker network create --driver=bridge --subnet=172.18.0.0/16 --gateway=172.18.0.1 traefik
# #

networks:
    traefik:
        name: traefik
        external: true
