#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Directories
SCRIPTS_DIR="/custom-cont-init.d"

# Make sure custom init directory exists and has files in it
if [[ -e "${SCRIPTS_DIR}" ]] && [[ -n "$(/bin/ls -A ${SCRIPTS_DIR} 2>/dev/null)" ]]; then
    echo -e " CustomInit   : Files found, executing"
    for SCRIPT in "${SCRIPTS_DIR}"/*; do
        NAME="$(basename "${SCRIPT}")"
        if [[ -f "${SCRIPT}" ]]; then
            echo -e " CustomInit   : Running ${NAME} - ${SCRIPT}"
            /bin/bash "${SCRIPT}"

            echo -e " CustomInit   : Exited ${NAME} - $?"
        elif [[ ! -f "${SCRIPT}" ]]; then
            echo -e " CustomInit   : Error - ${NAME} is not a file"
        fi
    done
else
    echo -e " CustomInit   : No custom files found, skipping"
fi
